language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: hhvm-nightly
    allow_failures:
        - php: 5.5
        - php: hhvm-nightly
    fast_finish: true

before_install:
    - composer self-update
    - if [[ "$TRAVIS_PHP_VERSION" != *"nightly" ]]; then phpenv config-rm xdebug.ini; fi;
    - if [[ "$TRAVIS_PHP_VERSION" != *"nightly" ]]; then php -i; fi;
    - sudo locale-gen en_US.UTF-8 && sudo update-locale
    - if [ "$TRAVIS_BRANCH" = "master" ]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION="$TRAVIS_BRANCH".x-dev; fi;

install:
    - composer --prefer-source install; fi;

scripts:
    - vendor/bin/phpunit --exclude-group tty,benchmark,intl-data
    - vendor/bin/behat
